name: PR Audit CI

on: [pull_request]

jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        run: sleep 30
      - name: Audit URLs using Lighthouse
        uses: jakejarvis/lighthouse-action@master
        with:
          netlify_site: 'tramspotter.netlify.com'
      - uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'
